#ifndef DATABASEPATH_H
#define DATABASEPATH_H

#define PLAY_DATA_PATH "./SOKOBANGAME/DATABASE/PlayData.txt"

#define DATA_STATE_PATH "./SOKOBANGAME/DATABASE/saveState_data.dat"

#define INDEX_DATA_STATE_PATH "./SOKOBANGAME/DATABASE/saveState_index.txt"

#define TEMP_INDEX_PATH "./SOKOBANGAME/DATABASE/temp_path.txt"

#define TEMP_PLAYDATA_PATH "./SOKOBANGAME/DATABASE/temp_PlayData.txt"

#define PLAY_DATA_BY_SCORE_PATH "./SOKOBANGAME/DATABASE/PlayData_sortedScore.txt"

#define PLAY_DATA_BY_NAME_PATH "./SOKOBANGAME/DATABASE/PlayData_sortedName.txt"


#endif // DATABASEPATH_H